# Generated by Django 5.2 on 2025-04-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut_user',
            field=models.IntegerField(unique=True),
        ),
    ]
